### ISSUE TITLE
General Improvement [META]

### ISSUE THREAD

**Issue by BeyondMagic** [BeyondMagic/home#2]
- [ ] Find character limit of quotes elements responsible to the screen and apply slider css
- [ ] Icon
- [ ] Complete Readme
- [ ] RSS Reader View
- [ ] Links View (move links, move sections, save in cache)
- [ ] Quotes View (See ID, next quote, previous quote, go to ID quote)
- [ ] Change Wallpaper w/ NODE
- [ ] Add quotes w/ NODE
- [ ] Add sections/links w/ NODE 
- [ ] Explain **aliases**
- [ ] Automatic build for changes **inserver**
- [x] SASS easy variables
